// <auto-generated />
using System;
using LabResults.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabResults.Infrastructure.Migrations
{
    [DbContext(typeof(LabResultsDbContext))]
    partial class LabResultsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabResults.Domain.Aggregates.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Samples", (string)null);
                });

            modelBuilder.Entity("LabResults.Domain.Aggregates.Sample", b =>
                {
                    b.OwnsOne("LabResults.Domain.Aggregates.AnalysisResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("SampleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ResultCompletedAt");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("ResultId");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ResultNotes");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ResultType");

                            b1.HasKey("SampleId");

                            b1.ToTable("Samples");

                            b1.WithOwner()
                                .HasForeignKey("SampleId");

                            b1.OwnsOne("LabResults.Domain.ValueObjects.ResultValue", "Value", b2 =>
                                {
                                    b2.Property<Guid>("AnalysisResultSampleId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Numeric")
                                        .HasColumnType("numeric")
                                        .HasColumnName("ResultNumeric");

                                    b2.Property<decimal>("ReferenceMax")
                                        .HasColumnType("numeric")
                                        .HasColumnName("ResultRefMax");

                                    b2.Property<decimal>("ReferenceMin")
                                        .HasColumnType("numeric")
                                        .HasColumnName("ResultRefMin");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("ResultUnit");

                                    b2.HasKey("AnalysisResultSampleId");

                                    b2.ToTable("Samples");

                                    b2.WithOwner()
                                        .HasForeignKey("AnalysisResultSampleId");
                                });

                            b1.Navigation("Value")
                                .IsRequired();
                        });

                    b.OwnsOne("LabResults.Domain.ValueObjects.DoctorId", "ValidatedBy", b1 =>
                        {
                            b1.Property<Guid>("SampleId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ValidatedById");

                            b1.HasKey("SampleId");

                            b1.ToTable("Samples");

                            b1.WithOwner()
                                .HasForeignKey("SampleId");
                        });

                    b.OwnsOne("LabResults.Domain.ValueObjects.PatientId", "PatientId", b1 =>
                        {
                            b1.Property<Guid>("SampleId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("PatientIdValue");

                            b1.HasKey("SampleId");

                            b1.ToTable("Samples");

                            b1.WithOwner()
                                .HasForeignKey("SampleId");
                        });

                    b.OwnsOne("LabResults.Domain.ValueObjects.SampleCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("SampleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Code");

                            b1.HasKey("SampleId");

                            b1.ToTable("Samples");

                            b1.WithOwner()
                                .HasForeignKey("SampleId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("PatientId")
                        .IsRequired();

                    b.Navigation("Result");

                    b.Navigation("ValidatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
